### PR TITLE
Switch the color of not availiable trains red

### PR DESCRIPTION
**Pull request by noriakisana**
Added possibility to modify objects depending on the train status

- card body
- button
- button text
- train image

current it changes the card body background to gray when the train isnt available.

### CODE REVIEW

**Review by eyip002 — CHANGES_REQUESTED** [review]
I can only see the changes related the card body. Can you add screenshots of the changes to the user interface?

To show that a train is unavailable, it would be better to disable the grab train button, change the button text to `Unavailable`/`Nicht verfügbar`, change the button colour to `var(--danger)`, and change the opacity of the train image to ~30%.

**Comment by noriakisana** [comment]
Train available:
image

Train unavailable:
image

**Comment by eyip002** [comment]
Screen Shot 2023-06-05 at 10 36 52

**Comment by eyip002** [comment]
Screenshot 2023-06-05 at 10 39 53

**Review by eyip002 — APPROVED** [review]

**Pull request merged**
